import json
import os

notebook_path = "notebooks/examine_validation.ipynb"

with open(notebook_path, "r") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell.get("id") == "plot_fluxes":
        source = [
            "\\n",
            "for out_dir in output_dirs:\\n",
            "    path = os.path.join(\\\"..\\\", out_dir)\\n",
            "\\n",
            "    flux_path = os.path.join(path, \\\"fluxes.npz\\\")\\n",
            "    growth_path = os.path.join(path, \\\"growth.npz\\\")\\n",
            "    kx_spec_path = os.path.join(path, \\\"kxspec.npz\\\")\\n",
            "    ky_spec_path = os.path.join(path, \\\"kyspec.npz\\\")\\n",
            "\\n",
            "    if not os.path.exists(flux_path) or not os.path.exists(growth_path):\\n",
            "        print(f\\\"Skipping {out_dir}: missing .npz files\\\")\\n",
            "        continue\\n",
            "\\n",
            "    sim_flux = np.load(flux_path)[\\\"fluxes\\\"]\\n",
            "    sim_time = np.load(growth_path)[\\\"time\\\"]\\n",
            "\\n",
            "    config_name = out_dir.replace(\\\"validation_outputs_\\\", \\\"\\\")\\n",
            "    config_path = os.path.join(\\\"..\\\", \\\"configs\\\", f\\\"{config_name}.yaml\\\")\\n",
            "\\n",
            "    ref_time = None\\n",
            "    ref_fluxes = None\\n",
            "    ref_kx_spec = None\\n",
            "    ref_ky_spec = None\\n",
            "\\n",
            "    if os.path.exists(config_path):\\n",
            "        cfg = load_config(config_path)\\n",
            "        ref_dir = cfg.run.data_dir\\n",
            "\\n",
            "        ref_time_path = os.path.join(ref_dir, \\\"time.dat\\\")\\n",
            "        ref_flux_path = os.path.join(ref_dir, \\\"fluxes.dat\\\")\\n",
            "\\n",
            "        if os.path.exists(ref_time_path) and os.path.exists(ref_flux_path):\\n",
            "            ref_time = np.loadtxt(ref_time_path)\\n",
            "            ref_fluxes = np.loadtxt(ref_flux_path).T\\n",
            "\\n",
            "        # Load full geometry from config\\n",
            "        geom = load_geometry(ref_dir)\\n",
            "        kx = np.asarray(geom[\\\"kxrh\\\"])\\n",
            "        ky = np.asarray(geom[\\\"krho\\\"])\\n",
            "\\n",
            "        # Time-averaged reference spectra\\n",
            "        avg_count = 80\\n",
            "        ref_kx_path = os.path.join(ref_dir, \\\"kxspec\\\")\\n",
            "        ref_ky_path = os.path.join(ref_dir, \\\"kyspec\\\")\\n",
            "\\n",
            "        if os.path.exists(ref_kx_path) and os.path.exists(ref_ky_path):\\n",
            "            try:\\n",
            "                rkx = np.loadtxt(ref_kx_path)\\n",
            "                rky = np.loadtxt(ref_ky_path)\\n",
            "                ref_kx_spec = np.mean(rkx[-avg_count:], axis=0)\\n",
            "                ref_ky_spec = np.mean(rky[-avg_count:], axis=0)\\n",
            "            except Exception as e:\\n",
            "                print(f\\\"Warning: failed to load reference spectra from {ref_dir}: {e}\\\")\\n",
            "\\n",
            "    # 3. Plot Fluxes\\n",
            "    fig = plot_flux_trace(\\n",
            "        sim_time,\\n",
            "        sim_flux.T[[1, 2]],\\n",
            "        ref_time=ref_time,\\n",
            "        ref_fluxes=ref_fluxes[[1, 2]],\\n",
            "        labels=[\\\"Heat\\\", \\\"Momentum\\\"],\\n",
            "        title=(\\n",
            "            f\\\"Fluxes: R/LT={cfg.physics.rlt:.1f}, R/LN={cfg.physics.rln:.1f}, \\\"\\n",
            "            f\\\"shat={cfg.geometry.shat:.1f}, q={cfg.geometry.q:.1f}\\\"\\n",
            "        )\\n",
            "    )\\n",
            "    fig.savefig(f\\\"figs/fluxes_{config_name}.pdf\\\")\\n",
            "\\n",
            "    # 4. Plot Spectra Comparison (Time-averaged)\\n",
            "    if os.path.exists(kx_spec_path) and os.path.exists(ky_spec_path):\\n",
            "        kx_data = np.load(kx_spec_path)\\n",
            "        ky_data = np.load(ky_spec_path)\\n",
            "        \\n",
            "        kx_spec_hist = kx_data[\\\"kx_spec\\\"]\\n",
            "        ky_spec_hist = ky_data[\\\"ky_spec\\\"]\\n",
            "        \\n",
            "        kx_spec_avg = np.mean(kx_spec_hist[-avg_count:], axis=0)\\n",
            "        ky_spec_avg = np.mean(ky_spec_hist[-avg_count:], axis=0)\\n",
            "        \\n",
            "        fig_spec = plot_spectra(\\n",
            "            kx=kx,\\n",
            "            ky=ky,\\n",
            "            kx_spec=kx_spec_avg,\\n",
            "            ky_spec=ky_spec_avg,\\n",
            "            ref_kx_spec=ref_kx_spec,\\n",
            "            ref_ky_spec=ref_ky_spec,\\n",
            "            title=(\\n",
            "                f\\\"Time-averaged Spectra (last {avg_count}): R/LT={cfg.physics.rlt:.1f}, \\\"\\n",
            "                f\\\"R/LN={cfg.physics.rln:.1f}, shat={cfg.geometry.shat:.1f}, q={cfg.geometry.q:.1f}\\\"\\n",
            "            )\\n",
            "        )\\n",
            "        fig_spec.savefig(f\\\"figs/spectra_{config_name}.pdf\\\")\\n",
            "    else:\\n",
            "        # Fallback to last dump if history not available\\n",
            "        last_step_files = sorted([f for f in os.listdir(path) if f.startswith(\\\"step_\\\") and f.endswith(\\\".npz\\\")])\\n",
            "        if last_step_files:\\n",
            "            last_dump = np.load(os.path.join(path, last_step_files[-1]))\\n",
            "            phi_final = last_dump[\\\"phi\\\"]\\n",
            "            \\n",
            "            fig_spec = plot_spectra(\\n",
            "                kx=kx,\\n",
            "                ky=ky,\\n",
            "                phi=phi_final,\\n",
            "                ref_kx_spec=ref_kx_spec,\\n",
            "                ref_ky_spec=ref_ky_spec,\\n",
            "                title=(\\n",
            "                    f\\\"Saturated Spectra (last dump): R/LT={cfg.physics.rlt:.1f}, \\\"\\n",
            "                    f\\\"R/LN={cfg.physics.rln:.1f}, shat={cfg.geometry.shat:.1f}, q={cfg.geometry.q:.1f}\\\"\\n",
            "                )\\n",
            "            )\\n",
            "            fig_spec.savefig(f\\\"figs/spectra_{config_name}.pdf\\\")\\n"
        ]
        cell["source"] = source
        break

with open(notebook_path, "w") as f:
    json.dump(nb, f, indent=2)
