run:
  name: kinetic_example
solver:
  dt: 0.004
  naverage: 100
  n_steps: 800
  dump_interval: 3
  disp_par: 1.0
  disp_vp: 0.2
  disp_x: 0.1
  disp_y: 0.1
  idisp: 2
  non_linear: true
  adaptive_dt: true
  finit: cosine2
physics:
  rlt: [5.4, 3.45]
  rln: [3.0, 3.0]
  mas: [1.0, 0.0003]
  tmp: [1.0, 1.0]
  de: [1.0, 1.0]
  signz: [1.0, -1.0]
geometry:
  geometry_model: circ
  shat: 2.74913
  q: 3.48731
  eps: 0.19
  Rref: 100.0
  signB: 1.0
  kymax: 0.5800079543948031
grid:
  nvpar: 32
  nmu: 8
  ns: 16
  nkx: 85
  nky: 32
  adiabatic_electrons: false
